### ISSUE TITLE
email with attachment

### ISSUE THREAD

**Issue by lengxiaolei** [Drillster/drone-email#17]
hi there 
 I used done-email to notify my CI result and go test result，and I used goreporter to generate a report.html too, how can I use dron-email to send  report.html as a attachment？

**Comment by lengxiaolei** [comment]
It seems that drone-email only send the build status but can not send a attach file

**Comment by mjwwit** [comment]
Interesting use case. I agree this can be useful in some situations, can you make a PR? If not I'll work on it when I find the time.

**Comment by lengxiaolei** [comment]
期待你的更新！

**Comment by mjwwit** [comment]
If you want everyone to understand you, please reply in English.

**Comment by lengxiaolei** [comment]
Very glad to receive your reply and I can't make a PR... Look forward to your update！

**Comment by mjwwit** [comment]
Fixed in 982dc51
