### ISSUE TITLE
feature request: username & password from secrets

### ISSUE THREAD

**Issue by mbsimonovic** [Drillster/drone-email#23]
like https://github.com/appleboy/drone-scp for example

**Comment by mjwwit** [comment]
This plugin already offers support for secrets. Can you take a look at [the docs](https://github.com/Drillster/drone-email/blob/master/DOCS.md#secrets-1) to see if this works for you?

**Comment by mbsimonovic** [comment]
perfect, I just went through the plugin docs at 
http://plugins.drone.io/drillster/drone-email/ and assume it doesn't support secrets because it's not mentioned..
