### ISSUE TITLE
documentation on plugins.drone.io is out of date

### ISSUE THREAD

**Issue by TonyApuzzo** [Drillster/drone-email#24]
Hi, I was pulling my hair out trying to use secrets until I found the documentation here.

The docs at: http://plugins.drone.io/drillster/drone-email/ seem to be old and don't list the actual secret names.

**Comment by mjwwit** [comment]
I've actually already created a PR for the docs to fix this, thanks for noticing though!
https://github.com/drone/drone-plugin-index/pull/166
