### ISSUE TITLE
port settings not working

### ISSUE THREAD

**Issue by webfrank** [Drillster/drone-email#25]
Hi, I configured the plugin this way:

`- name: notify
  image: drillster/drone-email
  host: x.x.x.x
  port: 25
  from: drone@domain.com
  when:
    status: [ changed, failure ]`

but it sill tries to connect to port 587

**Comment by mjwwit** [comment]
Interesting, I've never experienced any issues... What Drone version are you using?

**Comment by webfrank** [comment]
Hi, found the problem, was my fault not putting plugin configuration under settings: in yaml

**Comment by justinhauer** [comment]
@webfrank did you validate this works now? I am having the same problem

**Comment by webfrank** [comment]
Double check plugin configuration

**Comment by justinhauer** [comment]
@webfrank @mjwwit Here is my configuration, how should it look to move port from the default of 587?


- name: Notify Pipeline Failed
   image: drillster/drone-email:latest
   host: smtp.mycompany.com
   skip_verify: true
   port: 25
   from: me@myemail.com
   recipients: [myrecipient@myemail.com ]
   when:
   status: [ failure ]
