### ISSUE TITLE
drillster/drone-email and safety of password

### ISSUE THREAD

**Issue by ser** [Drillster/drone-email#26]
Hi, to use drillster/drone-email, as I can understand, I must provide mail relay password. It can be secret, but If I want pull requests to be announced by mail, I must privilege a pull requestor to access it, which IMHO is a security breach - as they can uncover it easily modifying the .drone.yml.

Am I correct and if yes, how can we provide this password in a safe way?

**Comment by mjwwit** [comment]
Yes, of course you want this to be kept securely. Luckily, Drone has a way to do this. You can find the docs here: https://docs.drone.io/user-guide/secrets/

**Comment by ser** [comment]
As I mentioned above, secrets are not safe, if PRs with secrets are allowed to be sent by general public. 

A random guy can add:

```
echo $SECRET
```
and you have this displayed in public.

**Comment by mjwwit** [comment]
I'm sorry, I must have misread. You can get around that by disallowing people to change the Drone config yaml: https://docs.drone.io/user-guide/signature/

**Comment by ser** [comment]
Thanks a lot, I was not aware of that drone functionality and it fully answers my question.
