### ISSUE TITLE
Don't fail on missing attachments

### ISSUE THREAD

**Issue by mawis** [Drillster/drone-email#30]
I consistent problem I have with this plugin is, that it fails if I configure an attachment, that isn't present.

I would like to send out the check results as an attachment to the generated e-mail. This works very well if the build succeeds. But actually the test results are even more important in case of a failure. When the build fails at one point, it doesn't execute further steps. So a test report created later in the build pipeline may not be present and sending out e-mails fails.

This is especially problematic as the first configured recipient still gets the e-mail, thinks the reporting did work, but all further configured recipients are not notified.

I think that this plugin just just skip attaching files, that are not present when the plugin runs.

**Comment by mjwwit** [comment]
> When the build fails at one point, it doesn't execute further steps.

That's not entirely correct. You can configure steps to execute even if a previous step failed.

> I think that this plugin just just skip attaching files, that are not present when the plugin runs.

I think it's a good idea not to let this plugin fail if an attachment isn't present. I'd love a PR for this if you're OK with writing Golang.

**Comment by mawis** [comment]
> That's not entirely correct. You can configure steps to execute even if a previous step failed.

Sure, but that is not intended. If the step that builds the binary, it makes no sence to run the integrations tests afterwards.

> I think it's a good idea not to let this plugin fail if an attachment isn't present. I'd love a PR for this if you're OK with writing Golang.

Let me try it :)
