### ISSUE TITLE
DRONE_COMMIT_AUTHOR_EMAIL not set on Github Pull requests

### ISSUE THREAD

**Issue by s00500** [Drillster/drone-email#41]
Hi everyone,

So I have an issue that I do not understand, maybe I just did not get the docs right:
When using this plugin on github pull requests the DRONE_COMMIT_AUTHOR_EMAIL is not set, therefore no email is sent out. (https://discourse.drone.io/t/drone-commit-author-name-and-drone-commit-author-email-are-not-available-for-pull-requests/4321)
Now I can use another pipeline step to write that email to a file or something but then I still can not use it in the plugin...

Using the recipients field is not an option, as we need to be able to have several different users using this  in the organisation and do not want to notify everyone else all the time.

Is there any option to get around this that exists ? otherwise I would maybe add a PR to load recipients emails from files...

Greetings,
Lukas

**Comment by mjwwit** [comment]
This is a tough one indeed... Sadly it's a limitation of GitHub, not of this plugin or of Drone itself. I think your proposal for reading the recipients from a file would be an acceptable solution. If you could make a PR for this that would be great!

**Comment by s00500** [comment]
PR is ready: #42
Can you push a new docker image after this ?

**Comment by s00500** [comment]
Alright thanks for the merge!

Here is the solution I planned to use:

Run this step before the email step:
```
 - name: get-commiters-details
   image: docker:git
   commands:
     - |
       echo $(git show -s --format='%ae' $DRONE_COMMIT) > .commiter_email
       echo $(git show -s --format='%cN' $DRONE_COMMIT) > .commiter_name
       cat .commiter_email
       cat .commiter_name
```

And then run email and set ".commiter_email" as recipients_file



This also works perfectly fine now....

BUT:

I have for some reason noticed today that it seems the DRONE_COMMIT_AUTHOR_EMAIL is populated now
I am not sure if github changed their request or if my update of the drone/drone image did the trick, but it works without any modification now.

Thanks a lot for your merge anyway, I guess this could be a useful feature still =D

**Comment by s00500** [comment]
Ok forget my last message, this is simply not true as I was confused by my pull event trigger
