### ISSUE TITLE
Pipeline with trigger and step with when condition does not fire

### ISSUE THREAD

**Issue by webfrank** [Drillster/drone-email#47]
Hi,
  I have a pipeline with a trigger and the notify with a when condition but the email is not sent:
  
  `kind: pipeline
type: docker
name: build

steps:
- name: build
  image: node:lts-alpine
  commands:
  - apk update
  - apk add git
  - npm install
  - npm run build
- name: package
  image: plugins/docker
  settings:
    auto_tag: true
    registry: xxxxxx
    repo: xxxxxxx
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
- name: notify
  image: drillster/drone-email
  settings:
    from: xxxxxxx
    host: xxxxxx
    port: xxxxx
    recipients:
      - xxxxx
  when:
    status:
      include:
      - success
      - failure

trigger:
  event:
  - tag`

This pipeline fires whenever I tag a version but the notify step is skipped also without the include:)

**Comment by mjwwit** [comment]
I'm not sure how I missed this... Sorry for the late response.
Please replace your notify step with some generic image and echo something. If this also doesn't work your problem is your pipeline and you should either refer to the Drone documentation or their community to locate and resolve your issue.

**Comment by webfrank** [comment]
Hi, I forgot about this issue. The problem was in gogs not firing the correct webhook. Updating gogs made the pipeline work again with failure and success email. Sorry to not have closed before the issue.
