### ISSUE TITLE
create_time error

### ISSUE THREAD

**Issue by Famine-Life** [Drillster/drone-email#48]
hi , bro, I'm Chinese ,  I find drone-email build message  has a time zone problem.

maybe, this is Docker's reason , I guess.

tell me yes or why ,please. thank you very mach.

**Comment by mjwwit** [comment]
The build create time in the default template will use the local time zone. You can change the time zone using the `TZ` environment variable.

**Comment by Famine-Life** [comment]
Hi, I tried to modify it many times, but no success.&nbsp;


always UTC.


can you give a demo?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Michael de ***@***.***&gt;; 
发送时间: 2021年7月8日(星期四) 下午4:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Drillster/drone-email] create_time error (#48)





 
The build create time in the default template will use the local time zone. You can change the time zone using the TZ environment variable.

**Comment by mjwwit** [comment]
Something like this should work:

```diff
steps:
  - name: notify
    image: drillster/drone-email
+   environment:
+     TZ: "Asia/Shanghai"
    settings:
      from: noreply@github.com
      host: smtp.mailgun.org
      recipients:
        - octocat@github.com

**Comment by mjwwit** [comment]
I'm assuming this fixed your issue. If not, feel free to respond.
