### ISSUE TITLE
load mail template from repo

### ISSUE THREAD

**Issue by glaszig** [Drillster/drone-email#49]
would you accept the idea to load a custom email template from a file inside the source directory/repo, e.g. `.drone/email/build.html`?

maintaining an email template inside yaml is... suboptimal, i think.

**Comment by mjwwit** [comment]
This is actually already supported, see [the docs](https://github.com/Drillster/drone-email/blob/master/DOCS.md#custom-templates).
You can set a URL for the template location, and `file://` URLs are supported.

**Comment by glaszig** [comment]
fantastic. thanks for the pointer. missed that skimming the docs.
