### ISSUE TITLE
Dockerfile arm binary drone-email error

### ISSUE THREAD

**Issue by igal-SX** [Drillster/drone-email#50]
Hi 
I need the email notification for arm servers.

I have built the correct docker with build and the dockerfile: Dockerfile.armhf

but when I run the container I got the error:
  
```standard_init_linux.go:228: exec user process caused: exec format error```

when I ran: docker run -it ...
I got: 

```
/ # /bin/drone-email 
/bin/drone-email: line 1: syntax error: unexpected ")"
```

I have tried to change the Golang version, but with no luck 

can you help how can I have it supported arm/v7 and v8?

**Comment by igal-SX** [comment]
Hi 

I have managed to compile it for arm with small change on the 

```FROM golang:1.14-alpine as builder```

to

```FROM golang:1.1**5**-alpine as builder```

and the build command:

```docker buildx build --file Dockerfile.armhf --platform linux/arm64/v7,linux/arm64 -t drone-email:latest . --push```

**Comment by mjwwit** [comment]
That's odd, but if the 1.15 base image solves this problem that would make a nice PR :smiley:

**Comment by mjwwit** [comment]
Fixed by your own PR, thanks!
