### ISSUE TITLE
support Gmail

### ISSUE THREAD

**Issue by igal-SX** [Drillster/drone-email#51]
Hi 

is this supports sending email to Gmail? if yes what is the procedure for username and password?

i have tried several options:

- google app password
- API key 
- client id and secret id

and nothing helped, the error I got:

```time="2021-09-14T13:08:21Z" level=error msg="Error while dialing SMTP server: 535 5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials o13sm8619455wri.53 - gsmtp" 
535 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials o13sm8619455wri.53 - gsmtp
```

**Comment by mjwwit** [comment]
I think Gmail still supports SMTP, so then this project should support Gmail, yes. I think your best bet is to Google for Gmails' SMTP settings.
