### ISSUE TITLE
TLS is disabled by default

### ISSUE THREAD

**Issue by elundblad** [Drillster/drone-email#58]
Hello,

I've noticed what seems a change in behavior as of [this PR](https://github.com/Drillster/drone-email/pull/57), that now requires `starttls: true` to be explicitly set to true to enable TLS.

I noticed my email sending using AWS SES no longer works in my drone builds with error

```
time="2021-11-01T07:15:45Z" level=error msg="Error while dialing SMTP server: unencrypted connection" 
```

However explicitly setting `starttls: true` works, but from how I understand the PR above it should be enabled by default

Thank you

**Comment by mjwwit** [comment]
It should default to `true`, yes. I thought I tested this as well... I will have a look at this later today.

**Comment by mjwwit** [comment]
I failed to notice that my testing mail server just accepted whatever starttls setting I gave it... Either way, I fixed the issue by flipping the `starttls` flag. It's now called `no_starttls` which you have to explicitly set to `true` to disable StartTLS.
