### ISSUE TITLE
Versioned tags removed from DockerHub

### ISSUE THREAD

**Issue by GarageParty** [Drillster/drone-email#59]
I've been using the 2.1.0 tag of the drone-email image in my Drone builds, but recently I noticed that all of the tags besides latest have been removed from DockerHub: https://hub.docker.com/r/drillster/drone-email/tags

Was that intentional? With only the latest tag available, any erroneous pushes will break everyone using this plugin until the next successful push.

**Comment by mjwwit** [comment]
I haven't removed them myself... Maybe they were removed by Docker when they removed the automated build? Either way I'll look into re-adding tags when I re-automate things using GitHub Actions.
