### ISSUE TITLE
[Feature request] Ignore email send error

### ISSUE THREAD

**Issue by mashirozx** [Drillster/drone-email#66]
In my case, the workflow failed due to the invalid Email address of the [dependabot](https://github.com/dependabot)'s auto commit.
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/16148054/170850300-207ea6d8-a1b3-45f7-bcef-9bffdb259583.png">

We need an option to bypass this~

**Comment by mjwwit** [comment]
Wouldn't you just be able to ignore the failure using Drone config like this: [https://docs.drone.io/pipeline/docker/syntax/steps/#failure](https://docs.drone.io/pipeline/docker/syntax/steps/#failure)?

**Comment by mashirozx** [comment]
oh, that is what I need, thank you 💖
